language: php

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
      env: COLLECT_COVERAGE=true

sudo: false

before_install:
- travis_retry composer self-update

install:
- travis_retry composer install --no-interaction --prefer-source
- if [[ "$COLLECT_COVERAGE" == "true" ]]; composer require satooshi/php-coveralls --dev; fi

script:
- if [[ "$COLLECT_COVERAGE" == "true" ]]; then php vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml; else php vendor/phpunit/phpunit/phpunit; fi

after_script:
- if [[ "$COLLECT_COVERAGE" == "true" ]]; then php vendor/bin/coveralls; fi
