language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
env:
matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: COLLECT_COVERAGE=true
  allow_failures:
    - php: nightly
    - php: 7.2
      env: COLLECT_COVERAGE=true

cache:
  directories:
    - $HOME/.composer/cache

install:
- travis_retry composer install --no-interaction --prefer-dist
- composer require php-coveralls/php-coveralls:^2 --dev --prefer-dist

script:
- if [[ "$COLLECT_COVERAGE" == "true" ]]; then php vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else php vendor/bin/phpunit --no-coverage; fi

after_script:
- if [[ "$COLLECT_COVERAGE" == "true" ]]; then php vendor/bin/coveralls; fi
